version: '3'

services:
  app:
    build: .
    container_name: app.local.dev
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./entrypoint.sh
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db
  db:
    build: ./.docker/mysql
    container_name: mysql.local.dev
    restart: unless-stopped
    tty: true
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=multitenancy
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - ${DB_LISTEN_PORT_OUT}:${DOCKER_LISTEN_PORT_IN}
# //etc/hosts
# //C:\Windows\system32\drivers\etc\hosts

# 127.0.0.1 host.docker.internal
